# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-07-30 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20200730_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='updated',
            new_name='update',
        ),
    ]
