# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-07-30 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='update',
        ),
    ]
